export const constants = {
  TEMPLATES: {
    MODERN: "modern",
    MINIMAL: "minimal",
    CREATIVE: "creative",
    PROFESSIONAL: "professional",
    SIDEBAR: "sidebar",
  },

  FONTS: {
    POPPINS: "'Poppins', sans-serif",
    ROBOTO: "'Roboto', sans-serif",
    OPEN_SANS: "'Open Sans', sans-serif",
    MONTSERRAT: "'Montserrat', sans-serif",
    RALEWAY: "'Raleway', sans-serif",
  },

  COLOR_SCHEMES: {
    LAVENDER: {
      primary: "#7B68EE",
      secondary: "#9370DB",
      accent: "#E6E6FA",
      text: "#424242",
      background: "#FFFFFF",
      title: "Lavender",
    },
    BLUE: {
      primary: "#1976d2",
      secondary: "#0d47a1",
      accent: "#bbdefb",
      text: "#263238",
      background: "#FFFFFF",
      title: "Blue",
    },
    TEAL: {
      primary: "#009688",
      secondary: "#00796b",
      accent: "#b2dfdb",
      text: "#263238",
      background: "#FFFFFF",
      title: "Teal",
    },
    CHARCOAL: {
      primary: "#455a64",
      secondary: "#263238",
      accent: "#cfd8dc",
      text: "#263238",
      background: "#FFFFFF",
      title: "Charcoal",
    },
    BURGUNDY: {
      primary: "#9c27b0",
      secondary: "#7b1fa2",
      accent: "#e1bee7",
      text: "#263238",
      background: "#FFFFFF",
      title: "Burgundy",
    },
    FOREST: {
      primary: "#2e7d32",
      secondary: "#1b5e20",
      accent: "#c8e6c9",
      text: "#263238",
      background: "#FFFFFF",
      title: "Forest",
    },
    MIDNIGHT: {
      primary: "#303f9f",
      secondary: "#1a237e",
      accent: "#c5cae9",
      text: "#263238",
      background: "#FFFFFF",
      title: "Midnight",
    },
    CORAL: {
      primary: "#e57373",
      secondary: "#c62828",
      accent: "#ffcdd2",
      text: "#263238",
      background: "#FFFFFF",
      title: "Coral",
    },
  },
};
